### ISSUE TITLE
[Bug Report] Docker container was not updated for latest release

### ISSUE THREAD

**Issue by CoderBrad** [jammsen/docker-sons-of-the-forest-dedicated-server#78]
### Have you read the Important information text above

- [x] Yes i did

### Current behavior

The FILTER_SHADER_AND_MESH environment variable doesn't work on the latest version available in docker hub

### Desired behavior

Be able to use the FILTER_SHADER_AND_MESH environment variable and have it effect the log output.

### To Reproduce

1. add example docker-compose.yml
2. run "docker compose up"
3. see that shader and mesh errors are showing up

### Software setup

- OS: Ubuntu 24.04.2 LTS
- Docker: 28.0.1

### Hardware setup

- vCPU: Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
- RAM: 96GB
- Disk: 500GB

### Additional context

If you go to hub.docker.com and look up the current version for the latest tag it shows the last push was 6 months ago while at the time of this report the latest commit that should have caused a build was 4 months ago. It looks like docker-build-and-push-master-ci hasn't run successfully since 9787aef and the new environment variable wasn't added until 124c214 .

**Comment by Cassian01** [comment]
i doo have the same error, since op didnt provide the logs i will.
allso if found the fillowing: `"@sSteamCmdForcePlatformType" = "windows"` since i dont know if thats supposed to be i note  it  here.

[_sons-of-the-forest-dedicated-server_logs (3).txt](https://github.com/user-attachments/files/21328417/_sons-of-the-forest-dedicated-server_logs.3.txt)


in the `game/userdata/dedicatedserver.cfg` i also turned on the logs:

[configstore_log.txt](https://github.com/user-attachments/files/21328474/configstore_log.txt)
[connection_log.txt](https://github.com/user-attachments/files/21328475/connection_log.txt)
[connection_log_8766.txt](https://github.com/user-attachments/files/21328478/connection_log_8766.txt)
[content_log.txt](https://github.com/user-attachments/files/21328472/content_log.txt)
[systemaudiomanager.txt](https://github.com/user-attachments/files/21328480/systemaudiomanager.txt)
[systemdisplaymanager.txt](https://github.com/user-attachments/files/21328476/systemdisplaymanager.txt)
[systemdockmanager.txt](https://github.com/user-attachments/files/21328479/systemdockmanager.txt)
[systemmanager.txt](https://github.com/user-attachments/files/21328477/systemmanager.txt)
[systemperfmanager.txt](https://github.com/user-attachments/files/21328473/systemperfmanager.txt)

**Comment by jammsen** [comment]
Hello @CoderBrad - This feature is only on develop, not on master, because its lacking testing-feedback. I run all my personal servers on the develop tag, because im the major tester for the images and features i build. 

I guess you could see it like this: 
If something hits master/latest i did at least run 3 times already , locally, remote (Dedicated-Server) and in the Unit-Test on GH.

See: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/compare/master...develop

So it wasnt released to master, therefore its not on the latest-tag, as it should be. BUT if you want to test this please use the develop tag and let me know if it works for you, you too @Cassian01 if you want.

Also - Hey @Cassian01 

> i doo have the same error, since op didnt provide the logs i will.
> allso if found the fillowing: `"@sSteamCmdForcePlatformType" = "windows"` since i dont know if thats supposed to be i note it here.

That small entry sets the "Platform" to download Windows under Linux, if i remove that, i cant download Windows-Software under Linux, because SteamCMD checks the architecture it runs off. If i would remove that you would never be able to "Download" TF/SOTF again, im not touch that 🤣 !

See: https://developer.valvesoftware.com/wiki/SteamCMD#Cross-Platform_Installation

So please, let me know what your tests found out, im happy to release it to master, if i get some testing feedback.

**Comment by CoderBrad** [comment]
I tried changing the tag from :latest to :develop for the image in the docker-compose but I'm still seeing the log entries in that. 
hub.docker.com is showing 6 months since the last push on that tag as well. Would I need to pull the repo and build the image myself for testing?

**Comment by jammsen** [comment]
I already asked for testing feedback in the discord too:
Invite-Link: https://discord.gg/7tacb9Q6tj - Channel: sons-of-the-forest-en - Message: https://discord.com/channels/532141442731212810/1201632296395096218/1396166391329198144

Im guessing your are missing the ENV - Read this: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/commit/124c214f3206d8456f05c75deb237b8e07cdc8df - It explains what to do with examples of hidden messages, only changing image-tags should be enough thoug 🤔

**Comment by jammsen** [comment]
> I tried changing the tag from :latest to :develop for the image in the docker-compose but I'm still seeing the log entries in that. hub.docker.com is showing 6 months since the last push on that tag as well. Would I need to pull the repo and build the image myself for testing?

Also remember, Docker-Compose ONLY provsions new ENVs on down + up, not on stop pull start.

**Comment by CoderBrad** [comment]
I did docker compose down and did docker rmi with the image ids and am still getting those errors. The docker compose up looks like this:
```
[+] Running 13/13
 ✔ sonsoftheforest Pulled                                                                                                                                                                               68.1s
   ✔ af302e5c37e9 Pull complete                                                                                                                                                                          3.2s
   ✔ e36385e2f0e6 Pull complete                                                                                                                                                                         10.2s
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                                         10.2s
   ✔ 4808058055c5 Pull complete                                                                                                                                                                         66.6s
   ✔ 35804cb57fd9 Pull complete                                                                                                                                                                         67.0s
   ✔ 43557ceed184 Pull complete                                                                                                                                                                         67.1s
   ✔ 1c164f926448 Pull complete                                                                                                                                                                         67.1s
   ✔ e129de9306a5 Pull complete                                                                                                                                                                         67.1s
   ✔ a901d7382fac Pull complete                                                                                                                                                                         67.2s
   ✔ 9fc7176974d9 Pull complete                                                                                                                                                                         67.2s
   ✔ 8c62c5f3ce79 Pull complete                                                                                                                                                                         67.2s
   ✔ f1d278196fd6 Pull complete                                                                                                                                                                         67.3s
[+] Running 1/1
 ✔ Container sonsoftheforest  Created                                                                                                                                                                    6.5s
Attaching to sonsoftheforest
sonsoftheforest  | > Current steam user PUID is '1000' and PGID is '1000'
sonsoftheforest  | > PUID and PGID matching what is requested for user steam
sonsoftheforest  | > id steam: uid=1000(steam) gid=1000(steam) groups=1000(steam)
sonsoftheforest  | >>> Starting server manager
sonsoftheforest  | > Started at: 2025-07-19 22:40:38
sonsoftheforest  | >>> Listing config options ...
sonsoftheforest  | > ALWAYS_UPDATE_ON_START is set to: true
sonsoftheforest  | > SKIP_NETWORK_ACCESSIBILITY_TEST is set to: false
sonsoftheforest  | >>> Server main thread started with pid 22
sonsoftheforest  | >>> Doing an update of the gameserver
```

So it doesn't list that config option during the "listing config options" phase.

My docker-compose is:
```   sonsoftheforest:
      container_name: sonsoftheforest
      image: jammsen/sons-of-the-forest-dedicated-server:develop
      restart: always
      environment:
         PUID: 1000
         PGID: 1000
         ALWAYS_UPDATE_ON_START: true
         SKIP_NETWORK_ACCESSIBILITY_TEST: false
         FILTER_SHADER_AND_MESH: true
      ports:
         - 10.1.1.26:8766:8766/udp
         - 10.1.1.26:27016:27016/udp
         - 10.1.1.26:9700:9700/udp
      volumes:
         - /docker/sonsoftheforest:/sonsoftheforest
```

As a test I cloned the develop branch locally and ran the docker-build.sh with a modified tag and when I switched to that image in my docker-compose the container correctly showed the environment variable was read during startup and the logs were properly filtered. The docker compose up looked like:
```
[+] Running 1/1
 ✔ Container sonsoftheforest  Created                                                                                                                                                                    0.1s
Attaching to sonsoftheforest
sonsoftheforest  | > Current steam user PUID is '1000' and PGID is '1000'
sonsoftheforest  | > PUID and PGID matching what is requested for user steam
sonsoftheforest  | > id steam: uid=1000(steam) gid=1000(steam) groups=1000(steam)
sonsoftheforest  | >>> Starting server manager
sonsoftheforest  | > Started at: 2025-07-19 22:58:52
sonsoftheforest  | >>> Listing config options ...
sonsoftheforest  | > ALWAYS_UPDATE_ON_START is set to: true
sonsoftheforest  | > SKIP_NETWORK_ACCESSIBILITY_TEST is set to: false
sonsoftheforest  | > FILTER_SHADER_AND_MESH is set to: true
sonsoftheforest  | >>> Server main thread started with pid 22
sonsoftheforest  | >>> Doing an update of the gameserver
```

**Comment by jammsen** [comment]
I might have killed the wrong build or so back then, i cant access the logs anymore, its to long gone. I fixed some workflow bugs and building the image right now.

**Comment by jammsen** [comment]
I now tried for hours to get it working and i have no idea whats going on, its always stuck on one of theese two events .... 

1)
```
#DSL [Self-Tests] Running self tests...
#DSL [Self-Tests] [AppId] App ID is correct.
#DSL [Self-Tests] [Settings] Validating game settings file format...
#DSL [Self-Tests] [Settings] Game settings file is valid.
#DSL [Self-Tests] [Config] Validating server config file and command line arguments...
#DSL Server configuration is valid. More...
{
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
```

2)
```
#DSL Loading progress: 66
#DSL Loading progress: 72
#DSL Loading progress: 72
#DSL Loading progress: 72
#DSL Loading progress: 72
#DSL Loading progress: 72
#DSL Loading progress: 72
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
#DSL Loading progress: 72
#DSL Loading progress: 72
#DSL Loading progress: 72
#DSL Loading progress: 73
#DSL Loading progress: 73
#DSL Loading progress: 73
#DSL Loading progress: 73
```

Both of them dont do anything beyond 15 minutes of time ...

**Comment by jammsen** [comment]
Reference:

- https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/actions/runs/16402379144/job/46343635026
- https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/actions/runs/16402864299/job/46344735734
- https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/actions/runs/16403014948/job/46345065460

**Comment by CoderBrad** [comment]
Interesting. I'm seeing the same behavior on my system when I run the image (I didn't notice previously because I closed it down as soon as I confirmed the environment variable was being used). It looks like if I set the filter to false it'll load up correctly though. Maybe something the grep command is filtering out? I'm going to play with it and see if I can sort that out.

**Comment by CoderBrad** [comment]
Looks like there is a buffering issue. I was able to fix it by adding stdbuf like this:
```
stdbuf -oL -eL wine64 "$GAME_PATH"/SonsOfTheForestDS.exe -userdatapath "$GAME_USERDATA_PATH" 2>&1 | stdbuf -oL grep -v -E ".*WARNING: Shader.*|.*ERROR: Shader.*|.*No mesh data available for mesh.*|.*Couldn't create a Convex Mesh from source.*|.*The referenced script.*|.*Could not find video decode shader pass.*"
```

The fixme lines are still showing up. It looks like wine changes its verbosity when piping?

**Comment by jammsen** [comment]
> Looks like there is a buffering issue. I was able to fix it by adding stdbuf like this:
> 
> ```
> stdbuf -oL -eL wine64 "$GAME_PATH"/SonsOfTheForestDS.exe -userdatapath "$GAME_USERDATA_PATH" 2>&1 | stdbuf -oL grep -v -E ".*WARNING: Shader.*|.*ERROR: Shader.*|.*No mesh data available for mesh.*|.*Couldn't create a Convex Mesh from source.*|.*The referenced script.*|.*Could not find video decode shader pass.*"
> ```
> 
> The fixme lines are still showing up. It looks like wine changes its verbosity when piping?

Thanks for the input, i will look at this hopefully tomorrow. Looking forward to it.

**Comment by jammsen** [comment]
> Looks like there is a buffering issue. I was able to fix it by adding stdbuf like this:
> 
> ```
> stdbuf -oL -eL wine64 "$GAME_PATH"/SonsOfTheForestDS.exe -userdatapath "$GAME_USERDATA_PATH" 2>&1 | stdbuf -oL grep -v -E ".*WARNING: Shader.*|.*ERROR: Shader.*|.*No mesh data available for mesh.*|.*Couldn't create a Convex Mesh from source.*|.*The referenced script.*|.*Could not find video decode shader pass.*"
> ```
> 
> The fixme lines are still showing up. It looks like wine changes its verbosity when piping?

Hey @CoderBrad - i finally solved it, it freaking took ages 😠

The output buffer did sadly not help at all for me 😢 thanks for the suggesting though!

However i figured out by A vs B vs C testing in 3 IDEs and 3 shell and reverse engineering over the last 50 commits or more that somewhere down the line Wine OR SteamCMD OR SOTF-DS changed something, that makes it LITTERALY IMPOSSBILE to make a successful NetworkAccessibilityTest, you HAVE TO HAVE the "SkipNetworkAccessibilityTest" set to true .... the server wont start until you do and just hang there for hours .... i tested it by accident 🤣 

Im working now on a fix and filtering even more noisy logs with WINE out, this should drastically reduce the logs and i will for sure make this a default-set to true, which is kinda a breaking change on develop, but also a new feature .... but i really do care more about clean logs to help people then to read WINE warnings i litteraly cant fix.

I will post again when im done, takes maybe 1-2 hours, then i will publish a new develop image, would be awesome if you could test it too.

**Comment by jammsen** [comment]
Yes it works and also the output buffer kinda fixed my new unit-testing format, so i even included that in the base-image now for "default" 🤣 

https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/actions/runs/16531452481/job/46757573546

Develop Image is up here:
https://hub.docker.com/r/jammsen/sons-of-the-forest-dedicated-server/tags

Have fun testing it 😃 my testing so far worked flawlessly.
@CoderBrad

**Comment by jammsen** [comment]
Closed because of inactivity
